sudo: false
language: java
jdk:
  - openjdk12
addons:
  apt:
    packages:
      - dos2unix
services:
  - mysql
env:
  PRO=CinemaStreamMicroservices
notifications:
  email: false
matrix:
  include:
    - before_install: cd SeanceApp
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=SeanceApp
    - before_install: cd GenreApp
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=GenreApp
    - before_install: cd FilmApp
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=FilmApp
    - before_install: cd CinemaApp
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=CinemaApp
    - before_install: cd DiscoveryService
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=DiscoveryService
    - before_install: cd ApiGatewayApp
      before_script: chmod +x gradlew
      script: gradlew clean test
      after_script: gradlew clean build
      env: PRO=ApiGatewayApp