sudo: false
language: java
jdk:
  - openjdk12
addons:
  apt:
    packages:
      - dos2unix
services:
  - mysql
env:
  PRO=CinemaStreamMicroservices
matrix:
  include:
      -
        before_script:
        - "cd SeanceApp"
        - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=SeanceApp
      -
        before_script:
          - "cd GenreApp"
          - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=GenreApp
      -
        before_script:
          - "cd FilmApp"
          - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=FilmApp
      -
        before_script:
          - "cd CinemaApp"
          - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=CinemaApp

      -
        before_script:
          - "cd DiscoveryService"
          - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=DiscoveryService
      -
        before_script:
          - "cd ApiGatewayApp"
          - "chmod +x gradlew"
        script: gradlew clean test
        after_script: gradlew clean build
        env: PRO=ApiGatewayApp
notifications:
  email: false