sudo: false
language: java
jdk:
  - oraclejdk12
addons:
  apt:
    packages:
      - dos2unix
services:
  - mysql
env: PRO=CinemaStreamMicroservice
matrix:
  include:
      -
        before_install:
          - "cd SeanceApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=SeanceApp
      -
        before_install:
          - "cd GenreApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=GenreApp
      -
        before_install:
          - "cd FilmApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=FilmApp
      -
        before_install:
          - "cd CinemaApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=CinemaApp
      -
        before_install:
          - "cd DiscoveryService"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=DiscoveryService
      -
        before_install:
          - "cd ApiGatewayApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        after_success:
          - "cd .."
          - "chmod +x gradlew"
          - ./gradlew coveralls
          - "cd $PRO"
        env:
          - PRO=ApiGatewayApp
#          - JVM_OPTS=-Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
notifications:
  email: false