sudo: false
language: java
jdk:
  - oraclejdk12
addons:
  apt:
    packages:
      - dos2unix
services:
  - mysql
branches:
  only:
    - master
env: PRO=CinemaStreamMicroservice
matrix:
  include:
      -
        before_install:
          - "cd ./Microservices/SeanceApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=SeanceApp
      -
        before_install:
          - "cd ./Microservices/GenreApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=GenreApp
      -
        before_install:
          - "cd ./Microservices/FilmApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=FilmApp
      -
        before_install:
          - "cd ./Microservices/CinemaApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=CinemaApp
      -
        before_install:
          - "cd ./Microservices/DiscoveryService"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        env: PRO=DiscoveryService
      -
        before_install:
          - "cd ./WebApp"
          - "chmod +x gradlew"
        script: ./gradlew clean test
        after_script: ./gradlew clean build
        after_success:
          - "cd .."
          - "chmod +x gradlew"
#          - ./gradlew coverageAll
          - "cd $PRO"
        env:
          - PRO=ApiGatewayApp
#          - JVM_OPTS=-Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
notifications:
  email: false