CREATE TABLE IF NOT EXISTS seance(
	cid BIGINT NOT NULL,
    fid BIGINT NOT NULL,
    begining DATE NOT NULL,
    CONSTRAINT seance_PK PRIMARY KEY(cid,fid),
    CONSTRAINT date_check CHECK( begining > CURDATE())
);
GO
CREATE TABLE IF NOT EXISTS ticket(
    tid BIGINT NOT NULL,
    price DECIMAL(20,13) NOT NULL,
    CONSTRAINT ticket_PK PRIMARY KEY(tid)
);